export const basicComponents = [
  {
    type: "input",
    icon: "icon-input",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      width: "100%",
      defaultValue: "",
      placeholder: "",
      readonly: false,
      disabled: false,
      maxlength: 100,
      showWordLimit: false,
      clearable: true,
      showLabel: true,
      required: false,
      dataType: "string",
      pattern: "",
    },
  },
  {
    type: "textarea",
    icon: "icon-diy-com-textarea",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      width: "100%",
      defaultValue: "",
      placeholder: "",
      readonly: false,
      disabled: false,
      maxlength: 200,
      showWordLimit: false,
      clearable: true,
      showLabel: true,
      required: false,
      dataType: "string",
      pattern: "",
    },
  },
  {
    type: "number",
    icon: "icon-number",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: 0,
      min: 0,
      max: 10,
      step: 1,
      precision: undefined,
      showLabel: true,
      disabled: false,
      controlsPosition: "",
      required: false,
    },
  },
  {
    type: "radio",
    icon: "icon-radio-active",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      inline: false,
      defaultValue: "",
      showLabel: true,
      options: [
        {
          value: "Option 1",
          label: "Option 1",
        },
        {
          value: "Option 2",
          label: "Option 2",
        },
        {
          value: "Option 3",
          label: "Option 3",
        },
      ],
      required: false,
      remote: false,
      remoteOptions: [],
      props: {
        value: "value",
        label: "label",
      },
      remoteFunc: "",
      disabled: false,
    },
  },
  {
    type: "checkbox",
    icon: "icon-check-box",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      inline: false,
      defaultValue: [],
      showLabel: true,
      options: [
        {
          value: "Option 1",
          label: "Option 1",
        },
        {
          value: "Option 2",
          label: "Option 2",
        },
        {
          value: "Option 3",
          label: "Option 3",
        },
      ],
      required: false,
      remote: false,
      remoteOptions: [],
      props: {
        value: "value",
        label: "label",
      },
      remoteFunc: "",
      disabled: false,
    },
  },
  {
    type: "time",
    icon: "icon-time",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "21:19:56",
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: "",
      arrowControl: false,
      format: "HH:mm:ss",
      required: false,
      showLabel: true,
    },
  },
  {
    type: "timerange",
    icon: "icon-date",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "",
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      startPlaceholder: "",
      endPlaceholder: "",
      arrowControl: false,
      format: "HH:mm:ss",
      required: false,
      showLabel: true,
    },
  },
  {
    type: "date",
    icon: "icon-date",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "",
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: "",
      type: "date",
      format: "yyyy-MM-dd",
      timestamp: false,
      required: false,
      showType: [
        {
          label: "year",
          value: "year",
          format: "yyyy",
        },
        {
          label: "month",
          value: "month",
          format: "yyyy-MM",
        },
        {
          label: "week",
          value: "week",
          format: "yyyy 第 WW 周",
        },
        {
          label: "date",
          value: "date",
          format: "yyyy-MM-dd",
        },
        {
          label: "datetime",
          value: "datetime",
          format: "yyyy-MM-dd HH:mm:ss",
        },
      ],
      showLabel: true,
    },
  },
  {
    type: "daterange",
    icon: "icon-date",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: [],
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      format: "yyyy-MM-dd",
      startPlaceholder: "",
      endPlaceholder: "",
      required: false,
      showLabel: true,
    },
  },
  {
    type: "datetimerange",
    icon: "icon-date",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "",
      readonly: false,
      disabled: false,
      clearable: true,
      startPlaceholder: "",
      endPlaceholder: "",
      type: "daterange",
      format: "yyyy-MM-dd HH:mm:ss",
      required: false,
      showLabel: true,
    },
  },
  {
    type: "rate",
    icon: "icon-pingfen1",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      width: "100%",
      defaultValue: null,
      max: 5,
      disabled: false,
      allowHalf: false,
      required: false,
      showLabel: true,
    },
  },
  {
    type: "color",
    icon: "icon-color",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "",
      disabled: false,
      showAlpha: false,
      required: false,
      showLabel: true,
    },
  },
  {
    type: "select",
    icon: "icon-select",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: "",
      multiple: false,
      disabled: false,
      clearable: false,
      placeholder: "",
      required: false,
      options: [
        {
          label: "Option 1",
          value: "Option 1",
        },
        {
          label: "Option 2",
          value: "Option 2",
        },
        {
          label: "Option 3",
          value: "Option 3",
        },
      ],
      remote: false,
      filterable: false,
      remoteOptions: [],
      props: {
        value: "value",
        label: "label",
      },
      remoteFunc: "",
      showLabel: true,
    },
  },
  {
    type: "switch",
    icon: "icon-switch",
    rules: [],
    labelWidth: undefined,
    options: {
      defaultValue: false,
      required: false,
      disabled: false,
      showLabel: true,
    },
  },
  {
    type: "slider",
    icon: "icon-slider",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultValue: 0,
      disabled: false,
      required: false,
      min: 0,
      max: 100,
      step: 1,
      showInput: false,
      range: false,
      showLabel: true,
    },
  },
  {
    type: "text",
    icon: "icon-wenzishezhi-",
    rules: [],
    labelWidth: undefined,
    options: {
      defaultValue: "This is a text",
      customClass: "",
      showLabel: true,
    },
  },
];

export const advanceComponents = [
  {
    type: "blank",
    icon: "icon-zidingyishuju",
    rules: [],
    labelWidth: undefined,
    options: {
      span: 24,
      defaultType: "String",
      showLabel: true,
    },
  },
  {
    type: "imgupload",
    icon: "icon-tupian",
    options: {
      defaultValue: [],
      size: {
        width: 100,
        height: 100,
      },
      span: 24,
      tokenFunc: "funcGetToken",
      token: "",
      domain: "https://tcdn.form.making.link/",
      disabled: false,
      length: 8,
      multiple: false,
      isQiniu: false,
      isDelete: false,
      min: 0,
      isEdit: false,
      action: "https://tools-server.making.link/api/transfer",
    },
  },
  {
    type: "editor",
    icon: "icon-fuwenbenkuang",
    labelWidth: undefined,
    options: {
      defaultValue: "",
      span: 24,
      showLabel: true,
    },
  },
  {
    type: "cascader",
    icon: "icon-jilianxuanze",
    labelWidth: undefined,
    rules: [],
    options: {
      defaultValue: [],
      span: 24,
      placeholder: "",
      disabled: false,
      clearable: false,
      remote: true,
      remoteOptions: [],
      props: {
        value: "value",
        label: "label",
        children: "children",
      },
      remoteFunc: "",
      showLabel: true,
    },
  },
];

export const layoutComponents = [
  {
    type: "grid",
    icon: "icon-grid-",
    labelWidth: undefined,
    options: {
      span: 24,
      gutter: 0,
      justify: "start",
      align: "top",
      columns: [
        {
          span: 12,
          list: [],
        },
        {
          span: 12,
          list: [],
        },
      ],
    },
  },
];

export default [
  {
    title: "fm.components.basic.title",
    children: basicComponents,
  },
  {
    title: "fm.components.advance.title",
    children: advanceComponents,
  },
  {
    title: "fm.components.layout.title",
    children: layoutComponents,
  },
];
