/**
 * 支持函数数据
 */
export default [
  {
    label: "数学函数",
    children: [
      {
        label: "ABS",
        value: "ABS()",
        example: "ABS(-5)可以返回5，也就是-5的绝对值",
        desc: "返回数字的绝对值",
      },
      {
        label: "AVG",
        value: "AVG()",
        example: "AVG(V)，V含有100、90、80，则返回90为平均值",
        desc: "返回所有参数的平均值，参数V是明细表（子表）的某一个数字控件",
      },
      {
        label: "COS",
        value: "COS()",
        example: "COS(0)返回1",
        desc: "返回-1到1之间的余弦值，参数A为角度",
      },
      {
        label: "COUNT",
        value: "COUNT()",
        example: "COUNT(V)，V含有数学、语文、英语，则返回3",
        desc: "统计参数列表中选项值的个数，参数V是明细表(子表)的某一个控件",
      },
      {
        label: "INT",
        value: "INT()",
        example: "INT(3.1415)返回3，也就是3.1415的整数部分",
        desc: "将数字向下取整为最接近的整数",
      },
      {
        label: "LOG",
        value: "LOG()",
        example: "LOG(number,[base])",
        desc: "根据底数返回指定数字的对数，如LOG(9, 3)返回的结果是2",
      },
      {
        label: "MAX",
        value: "MAX()",
        example: "MAX(V)，V含有100、90、80，则返回100为最大值",
        desc: "返回参数列表中的最大值，参数V是明细表（子表）的某一个数字字段",
      },
      {
        label: "MIN",
        value: "MIN()",
        example: "MIN(V)，V含有100、90、80，则返回80为最小值",
        desc: "返回参数列表中的最小值，参数V是明细表（子表）的某一个数字字段",
      },
      {
        label: "MOD",
        value: "MOD()",
        example: "MOD(4,3)返回1，也就是4/3的余数",
        desc: "返回两数相除的余数，数字1是被除数，数字2是除数",
      },
      {
        label: "PI",
        value: "PI()",
        example: "PI",
        desc: "圆周率3.1415...",
      },
      {
        label: "POWER",
        value: "POWER()",
        example: "POWER(number,power)",
        desc: "返回指定数字的乘幂，如POWER(3，2)返回9，即3的2次方",
      },
      {
        label: "RAND",
        value: "RAND()",
        example: "RAND()",
        desc: "返回大于等于0且小于1的均匀分布随机实数，每一次触发计算都会变化",
      },
      {
        label: "ROUND",
        value: "ROUND()",
        example: "ROUND(3.1485,2)返回3.15",
        desc: "将数字四舍五入到指定的位数",
      },
      {
        label: "SIN",
        value: "SIN()",
        example: "SIN(90)返回0.8939966636005579",
        desc: "返回-1到1之间的正弦值，参数A为角度",
      },
      {
        label: "SQRT",
        value: "SQRT()",
        example: "SQRT(9)返回3，也就是9的正平方根",
        desc: "获取一个数字的正平方根，数字为非负数",
      },
      {
        label: "SUM",
        value: "SUM()",
        example: "SUM(V),V含有10、20、30，则返回60",
        desc: "统计输入参数的数值之和，参数V是明细表（子表）的某一个数字字段",
      },
      {
        label: "ADD",
        value: "ADD()",
        example: "ADD(0.3, 0.3, 0.3), 则返回0.9",
        desc: "统计输入参数的数值之和，可以传入多个参数（消除系统误差）",
      },
      {
        label: "SUBTRACT",
        value: "SUBTRACT()",
        example: "SUBTRACT(0.91, 0.9), 则返回0.01",
        desc: "两个数相减（消除系统误差）",
      },
      {
        label: "MULTIPLY",
        value: "MULTIPLY()",
        example: "MULTIPLY(2, 3), 2乘以3 返回6",
        desc: "两个数相乘（消除系统误差）",
      },
      {
        label: "DIVIDE",
        value: "DIVIDE()",
        example: "DIVIDE(4, 2), 4除以2则返回2",
        desc: "两个数相除（消除系统误差）",
      },
    ],
  },
  {
    label: "文本函数",
    children: [
      {
        label: "CONTAINS",
        value: "CONTAINS()",
        example: 'CONTAINS("ABC","B")返回true',
        desc: "判断参数1是否包含参数2的值，包含则返回true，不包含则返回false",
      },
      {
        label: "LEFT",
        value: "LEFT()",
        example: 'LEFT("数智云应用搭建工具",3)返回"数智云"，也就是"数智云应用搭建工具"的从左往右的前3个字符',
        desc: "从一个文本的第一个字符开始返回指定个数的字符",
      },
      {
        label: "LEN",
        value: "LEN()",
        example: 'LEN("数智云应用搭建工具")返回9，因为文本中有9个字符',
        desc: "获取文本中的字符个数",
      },
      {
        label: "LOWER",
        value: "LOWER()",
        example: 'LOWER("TEST")返回"test"',
        desc: "将一个文本中的所有大写字母转换为小写字母",
      },
      {
        label: "MID",
        value: "MID()",
        example: 'MID("数智云应用搭建工具",6,4)返回"搭建工具"',
        desc: "MID返回文本中从指定位置开始的指定数目的字符",
      },
      {
        label: "REPLACE",
        value: "REPLACE()",
        example: 'REPLACE("数智云应用搭建工具",4,6,"企业数据管理平台")返回"数智云企业数据管理平台"',
        desc: "根据指定的字符数，将部分文本替换为不同的文本",
      },
      {
        label: "RIGHT",
        value: "RIGHT()",
        example: 'RIGHT("数智云应用搭建工具",4)返回"搭建工具"，也就是"数智云应用搭建工具"从右往左的前4个字符',
        desc: "从文本字符串的最后一个字符开始返回指定个数的字符，若不填指定个数则取默认值1",
      },
      {
        label: "SEARCH",
        value: "SEARCH()",
        example: 'SEARCH("工具","数智云应用搭建工具",1)返回8',
        desc: "获取文本1在文本2中的开始位置，其中开始位置编码为在文本2中第几个位置开始查找",
      },
      {
        label: "STARTSWITH",
        value: "STARTSWITH()",
        example: 'STARTSWITH("数智云应用搭建工具","数智云")返回true',
        desc: "判断文本字符串是否以特定字符串开始，是则返回true，否则返回false",
      },
      {
        label: "SUBSTITUTE",
        value: "SUBSTITUTE()",
        example: 'SUBSTITUTE("数智云低代码搭建工具","低代码","应用")，返回"数智云应用搭建工具"',
        desc: "将文本字符串中的部分字符替换成新字符串",
      },
      {
        label: "TRIM",
        value: "TRIM()",
        example: 'TRIM(" 数智云 ")返回"数智云"',
        desc: "删掉文本首尾的空格",
      },
      {
        label: "UPPER",
        value: "UPPER()",
        example: 'UPPER("test")返回"TEST"',
        desc: "将一个文本中的所有小写字母转换成大写字母",
      },
    ],
  },
  {
    label: "时间函数",
    children: [
      {
        label: "ADDDAY",
        value: "ADDDAY()",
        example: 'ADDDAY("2020-01-15",5)返回2020-01-20',
        desc: "将指定日期加/减指定天数，当指定天数为负数时在日期上减去此天数",
      },
      {
        label: "ADDMONTH",
        value: "ADDMONTH()",
        example: 'ADDMONTH("2020-01-15",5)返回2020-06-15',
        desc: "将指定日期加/减指定月数，当指定月数为负数时在此日期上减去此月数",
      },
      {
        label: "ADDYEAR",
        value: "ADDYEAR()",
        example: 'ADDYEAR("2020-01-15",1)返回2021-01-15',
        desc: "将指定日期加/减指定年数，当指定年数为负数时在此日期上减去此年数",
      },
      {
        label: "DATE",
        value: "DATE()",
        example: 'DATE("2020-01-15 12:00:00")返回2020-01-15',
        desc: "将年月日时分秒转换为日期",
      },
      {
        label: "DAY",
        value: "DAY()",
        example: 'DAY("2020-01-15") 返回15',
        desc: "返回日期的天数，值为介于1到31之间的整数",
      },
      {
        label: "DAYS",
        value: "DAYS()",
        example: 'DAYS("2020-01-31","2020-01-10")返回21',
        desc: "返回两个日期之间的天数差值，精确到两位小数",
      },
      {
        label: "HOUR",
        value: "HOUR()",
        example: 'HOUR("2020-01-15 12:01:01")返回12',
        desc: "返回时间的小时部分",
      },
      {
        label: "HOURS",
        value: "HOURS()",
        example: 'HOURS("2020-01-15 13:01:01", "2020-01-15 12:01:01") 返回1',
        desc: "返回两个时间之间的小时数，精确到两位小数",
      },
      {
        label: "MINUTE",
        value: "MINUTE()",
        example: 'MINUTE("2020-01-15 12:05:01") 返回5',
        desc: "返回时间的分钟部分",
      },
      {
        label: "MINUTES",
        value: "MINUTES()",
        example: 'MINUTES("2020-01-15 13:05:01", "2020-01-15 12:05:01") 返回60',
        desc: "返回两个时间之间的分钟数，精确到两位小数",
      },
      {
        label: "MONTH",
        value: "MONTH()",
        example: 'MONTH("2020-08-01")返回8',
        desc: "返回日期月份，值为介于1到12之间的整数",
      },
      {
        label: "NOW",
        value: "NOW()",
        example: "NOW()返回当前时间",
        desc: "返回当前时间，精确到时分秒，格式为yyyy-MM-dd hh:mm:ss",
      },
      {
        label: "QUARTER",
        value: "QUARTER()",
        example: 'QUARTER("2020-12-14")返回4',
        desc: "返回日期的所属季度，值为介于1到4的整数",
      },
      {
        label: "TODAY",
        value: "TODAY()",
        example: "TODAY()返回今天日期",
        desc: "返回今天的日期，格式为：yyyy-MM-dd",
      },
      {
        label: "WEEKDAY",
        value: "WEEKDAY()",
        example: 'WEEKDAY("2020-12-14")返回1',
        desc: "返回指定日期为星期几",
      },
      {
        label: "WEEKNUM",
        value: "WEEKNUM()",
        example: 'WEEKNUM("2021-6-1")返回23',
        desc: "返回一个数字，该数字代表指定日期是一年中的第几周",
      },
      {
        label: "WEEKNUMISO",
        value: "WEEKNUMISO()",
        example: 'WEEKNUMISO("2021-6-1")返回22',
        desc: "返回一个数字，该数字代表指定日期是一年中的第几周（ISO标准周）",
      },
      {
        label: "YEAR",
        value: "YEAR()",
        example: 'YEAR("2020-01-15")返回2020',
        desc: "返回日期的年份",
      },
      {
        label: "YEARS",
        value: "YEARS()",
        example: 'YEARS("2020-01-31","2018-01-31")返回2',
        desc: "返回两个日期之间的年数差值，精确到两位小数",
      },
    ],
  },
  {
    label: "逻辑函数",
    children: [
      {
        label: "CASE",
        value: "CASE()",
        example: "CASE(条件表达式1,条件表达式1为true返回该值,条件表达式2,条件表达式2为true返回该值,...)",
        desc: "判断是否满足一个或多个条件，且返回符合第一个TRUE条件的值，CASE可以取代多个IF语句嵌套。",
      },
      {
        label: "IF",
        value: "IF()",
        example: 'IF(语文成绩>60,"及格","不及格")，当语文成绩>60是返回及格，否则返回不及格',
        desc: "判断一个条件能否满足；如果满足返回一个值，如果不满足则返回另外一个值",
      },
      {
        label: "AND",
        value: "AND",
        example: "表达式1 AND 表达式2",
        desc: "多个用AND连接的表达式,当所有表达式均为true时，表达式返回true，否则返回False",
      },
      {
        label: "OR",
        value: "OR",
        example: "表达式1 OR 表达式2",
        desc: "多个用OR连接的表达式，只要有一个表达式为true，表达式返回true",
      },
    ],
  },
  {
    label: "其他函数",
    children: [
      {
        label: "GETADDRESS",
        value: "GETADDRESS()",
        example: "GETADDRESS(地址字段)",
        desc: "将地址字段的值转换为文本",
      },
      {
        label: "ISNULL",
        value: "ISNULL()",
        example: "ISNULL(W)",
        desc: "判断是否为空，为空则返回true，不为空则返回false，可用于判断具体值或者某个字段,w可传为一个控件",
      },
    ],
  },
];
